apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  project: default
  source:
    repoURL: https://github.com/stockpedia/stockpedia-backend.git
    targetRevision: main
    path: kube/argocd/cluster-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: false
      selfHeal: false