apiVersion: v1
kind: Service
metadata:
  name: backend-service-nodeport-ktb
  namespace: {{ .Release.Namespace }}
  labels:
    project: ktb
    team: backend
    env: prod
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: ktb
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    app: backend
    env: prod
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
