apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-portainer-ktb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/part-of: ktb
    app.kubernetes.io/managed-by: Helm