apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc-ktb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/part-of: ktb
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: portainer-storageclass-local-ktb
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  selector:
    matchLabels:
      app.kubernetes.io/component: portainer